// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcrlxgfwzxuvqztmvrvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhjcmx4Z2Z3enh1dnF6dG12cnZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE5Mjk0OTYsImV4cCI6MjA4NzUwNTQ5Nn0.k3vZqzvjUeyrG6cDkU2SD0TOA7bbVktMJtdAPNcU9mY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});